#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
BRENDA data fields and units of measurement.

``fields`` maps the field names used by the BRENDA JSON schema
(https://www.brenda-enzymes.org/schemas/docs/2.0.0) to a human-readable
description. ``DATA_FIELDS`` lists the fields stored as arrays of value records.
"""

fields = {
    "id": "EC number",
    "recommended_name": "accepted name (IUBMB)",
    "systematic_name": "systematic name",
    "history": "information on deletions or transfers",
    "synonyms": "synonyms",
    "reaction": "reaction catalysed",
    "reaction_type": "reaction type",
    "natural_substrates_products": "natural substrates/products (reversibility in {...})",
    "substrates_products": "substrates/products (reversibility in {...})",
    "turnover_number": "turnover number, substrate in {...}",
    "km_value": "KM-value, substrate in {...}",
    "ki_value": "Ki-value, inhibitor in {...}",
    "kcat_km_value": "Kcat/KM-value, substrate in {...}",
    "specific_activity": "specific activity",
    "ic50_value": "IC-50 value",
    "ph_optimum": "pH optimum",
    "ph_range": "pH range",
    "ph_stability": "pH stability",
    "temperature_optimum": "temperature optimum",
    "temperature_range": "temperature range",
    "temperature_stability": "temperature stability",
    "pi_value": "isoelectric point",
    "molecular_weight": "molecular weight",
    "subunits": "subunits",
    "cofactor": "cofactor",
    "metals_ions": "metals/ions",
    "inhibitor": "inhibitors",
    "activating_compound": "activating compound",
    "protein": "protein",
    "protein_variants": "engineering",
    "posttranslational_modification": "posttranslational modification",
    "source_tissue": "source/tissue",
    "localization": "localization",
    "application": "application",
    "general_information": "general information on enzyme",
    "general_stability": "general stability",
    "storage_stability": "storage stability",
    "organic_solvent_stability": "organic solvent stability",
    "oxidation_stability": "oxygen stability",
    "expression": "expression",
    "cloned": "cloned",
    "purification": "purification",
    "renatured": "renatured",
    "crystallization": "crystallization",
    "reference": "references",
}

# Fields stored as arrays of {value, proteins, references, comment} records.
DATA_FIELDS = [
    "synonyms",
    "reaction",
    "reaction_type",
    "natural_substrates_products",
    "substrates_products",
    "turnover_number",
    "km_value",
    "ki_value",
    "kcat_km_value",
    "specific_activity",
    "ic50_value",
    "ph_optimum",
    "ph_range",
    "ph_stability",
    "temperature_optimum",
    "temperature_range",
    "temperature_stability",
    "pi_value",
    "molecular_weight",
    "subunits",
    "cofactor",
    "metals_ions",
    "inhibitor",
    "activating_compound",
    "protein_variants",
    "posttranslational_modification",
    "source_tissue",
    "localization",
    "application",
    "general_information",
    "general_stability",
    "storage_stability",
    "organic_solvent_stability",
    "oxidation_stability",
    "expression",
    "cloned",
    "purification",
    "renatured",
    "crystallization",
    "history",
]

units = {
    "km_value": "mM",
    "ki_value": "mM",
    "kcat_km_value": "$mM^{-1}.s^{-1}$",
    "ic50_value": "mM",
    "turnover_number": "$s^{-1}$",
    "specific_activity": "$µmol.min^{-1}.mg^{-1}$",
    "temperature_optimum": "${}^oC$",
    "temperature_range": "${}^oC$",
    "temperature_stability": "${}^oC$",
    "molecular_weight": "Da",
}
